django_poll/mysite/hunts/urls.py
from django.urls import path,include


from . import views
app_name = 'hunts'
urlpatterns = [
	path('',views.HuntView.as_view(),name='index'),
	path('<int:pk>/',views.DetailView.as_view(),name = 'detail'),
	path('<int:hunt_id>/sub/',views.sub,name='sub'),
	path('wrong/',views.Wrong.as_view(),name = 'wrong'),
	path('right/',views.Right.as_view(),name='right'),
	path('done/',views.Done.as_view(),name='done'),
	path('answered/',views.Answered.as_view(),name='answered'),
	path('nested_admin/', include('nested_admin.urls')),

]

django_poll/mysite/hunts/models.py
import datetime

from django.db import models
from django.utils import timezone
# for quiz
from django.contrib.auth.models import User, Group
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

class HuntClue(models.Model):
    clue_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.clue_text

 
class ClueAnswer(models.Model):
    clue = models.ForeignKey(HuntClue, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
       return self.answer_text

class Hunt(models.Model):
	name = models.CharField(max_length=1000)
	stops_count = models.IntegerField(default=0)
	description = models.CharField(max_length=70)
	created = models.DateTimeField(auto_now_add=True,null=True,blank=True)
	slug = models.SlugField()
	roll_out = models.BooleanField(default=False)
	def __str__(self):
		return self.name

class Meta:
	ordering = ['created',]
	verbose_name_plural ="Hunts"

	def __str__(self):
		return self.name

class Stop(models.Model):
	hunt = models.ForeignKey(Hunt, on_delete=models.CASCADE)
	label = models.CharField(max_length=1000)
	order = models.IntegerField(default=0)

	def __str__(self):
		return self.label
class Answer(models.Model):
	stop = models.ForeignKey(Stop, on_delete=models.CASCADE)
	text = models.CharField(max_length=1000)
	is_correct = models.BooleanField(default=False)
	
	def __str__(self):
		return self.text

class Usrs(models.Model):
	#usr = models.ForeignKey(User, on_delete=models.CASCADE)
	hunt = models.ForeignKey(Hunt, on_delete=models.CASCADE)
	usr = models.CharField(max_length=250,default="")
	correct_answers = models.IntegerField(default=0)
	#correct = models.ForeignKey(Answer, on_delete=models.CASCADE)
	completed = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.usr

class Corrects(models.Model):
	# usrs = models.ForeignKey(Usrs, on_delete=models.CASCADE)
	usr = models.CharField(max_length=250,default="")
	correct = models.CharField(max_length=500, default="")
	def __str__(self):
		return self.correct

class Response(models.Model):
	usr = models.ForeignKey(Usrs, on_delete=models.CASCADE)
	stop = models.ForeignKey(Stop, on_delete=models.CASCADE)
	answer = models.ForeignKey(Answer,on_delete=models.CASCADE,null=True,blank=True)

	def __str__(self):
		return self.stop.label
	@receiver(post_save, sender=Hunt)
	def set_default_hunt(sender, instance, created,**kwargs):
		hunt = Hunt.objects.filter(id = instance.id)
		hunt.update(stops_count=instance.stop_set.filter(hunt=instance.pk).count())

	@receiver(post_save, sender=Stop)
	def set_default(sender, instance, created,**kwargs):
		hunt = Hunt.objects.filter(id = instance.hunt.id)
		hunt.update(stops_count=instance.hunt.stop_set.filter(hunt=instance.hunt.pk).count())

	@receiver(pre_save, sender=Hunt)
	def slugify_title(sender, instance, *args, **kwargs):
		instance.slug = slugify(instance.name)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name='regular'))

django_poll/mysite/hunts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render,redirect
from django.urls import reverse
from django.views import generic

from .models import HuntClue, ClueAnswer, Hunt, Stop, Answer, Response, Usrs, Corrects
##from ../accounts/views import SignUp
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required

from django.db.models import F

from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

def index(request):
    return HttpResponse("Hello world")

class Done(generic.TemplateView):
    template_name = 'hunts/done.html'

class Answered(generic.TemplateView):
    template_name = 'hunts/answered.html'

class Right(generic.TemplateView):
    template_name = 'hunts/right.html'

class Wrong(generic.TemplateView):
    template_name = 'hunts/wrong.html'

class HuntView(generic.ListView):
    template_name = 'hunts/index.html'
    context_object_name = 'latest_hunt_list'

    def get_queryset(self):
        return Hunt.objects.all()

class DetailView(generic.DetailView):
    model = Hunt
    template_name = 'hunts/detail.html'

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

#@permission_required('hunts.add_response', login_url="/hunts/")
#@user_is_blog_post_user
def sub(request,hunt_id):
    hunt = get_object_or_404(Hunt, pk=hunt_id)
    stops = hunt.stop_set.all()
    u = request.user.username
    try:
        user = Usrs.objects.get(usr=u)
    except: 
        user = Usrs(usr=u,hunt=hunt)

    ans = Answer.objects.get(pk=request.POST['answer']) #return a type of Answer to ans
    try:
        cor = Corrects.objects.get(usr=user.usr,correct=ans.text)
        #uco = Corrects.objects.get(usrs=user)
        x = 0
    except:
        cor = Corrects(correct=ans.text,usr=user.usr)
        x = 1

    if ans.is_correct and (x==1):
        user.correct_answers+=1
        #cor.usrs = user
        #cor.correct = ans
        user.save()
        cor.save()
        if (user.correct_answers<5): 
            return HttpResponseRedirect('/hunts/right/')
        else:
            return HttpResponseRedirect('/hunts/done/')
    elif ans.is_correct and (x==0):
        return HttpResponseRedirect('/hunts/answered/')
    else:
        return HttpResponseRedirect('/hunts/wrong/')
    

django_poll/mysite/hunts/templates/hunts/answered.html
 <html>
   <body> 
      You have already answered the question.
      <p><a href="/hunts">Take me back to the hunt!</a></p>
   </body>
</html>

django_poll/mysite/hunts/templates/hunts/detail.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Hunt: {{hunt.name}}</title>
  </head>
  <body class="body" style="background-color:#aebfc2">
	<div class="container-fluid" style="min-height:95%; ">
      <div class="row justify-content-center">
        <div class="col-8">
          <h6 class="mt-2">Social Scavenger</h1>
          <hr class="mt-0 mb-4">
         <h1>{{ hunt.name }}</h1>

			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
			<form action="{% url 'hunts:sub' hunt.id %}" method="post">
			{% csrf_token %}
			{% for stop in hunt.stop_set.all %}
				<p>{{ stop.label }}</p>
				{% for answer in stop.answer_set.all %}
				    <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}">
				    <label for="answer{{ forloop.counter }}">{{ answer.text }}</label><br>

				{% endfor %}
				
			{% endfor %}
			<input type="submit" value="Submit">
</form> 
        </div>
      </div>
    </div>
  </body>
</html>

django_poll/mysite/hunts/templates/hunts/done.html
 <html>
   <body> 
      You have finished everything!
      <p><a href="/hunts">Take me back to the hunt!</a></p>
   </body>
</html>

django_poll/mysite/hunts/templates/hunts/index.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Social Scavenger - Main Page</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	
	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#aebfc2">
	<div class="container-fluid" style="min-height:95%; ">

		<div class="row">
			<div class="col-sm-10">
				  <br>
				  <center>
				  <h2>Social Scavenger Hunt!</h2>
				  <h3>Welcome to the list of hunts</h3>
				  <h4>Click on any hunt to begin</h4>
				  </center>
			  </div>

			  <div class="col-sm-2">
				  <br>
					<center>
						<h5>Group 15, EC601A2</h5>
						<h5></h5>
						<h6>Hu, Nitwari, O'Neill, Reardon</h6> 
					</center>
			  </div>
			  
		</div><hr>
    <div class='container-fluid'>
			<br><br>
   		 {% if latest_hunt_list %}
           <ul>
           {% for hunt in latest_hunt_list %}
           <li><a href="{% url 'hunts:detail' hunt.id %}" style="color:black">{{ hunt.name }}</a></li>
            {% endfor %}
                 </ul>
            {% else %}
                 <p>No hunts are available.</p>
            {% endif %}	
	</div>
		
	<footer>
		<div class="container-fluid" style='margin-left:15px'>
			<p><a>Copyright 2019 Social Scavenger Group</a></p>
		</div>
	</footer>	
	
</body>

</html>

django_poll/mysite/hunts/templates/hunts/right.html
 <html>
   <body> 
      fantastic, you now have earned points.
	  <p><a href="/hunts">Take me back to the hunt!</a></p>
   </body>
</html>

django_poll/mysite/hunts/templates/hunts/wrong.html
 <html>
   <body> 
      unfortunately, the answer is not correct.
      <p><a href="/hunts">Take me back to the hunt!</a></p>
   </body>
</html>